ARG FLUX
FROM fluxcd/flux:${FLUX}

ENV PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/lib/kubeyaml

RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/community git-crypt
